### ISSUE TITLE
Fix romi-dashboard zoom out for airport demo

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#115]
It seems large maps can't zoom out far enough. The attached picture is using the maximum zoom out.

![image](https://user-images.githubusercontent.com/11761240/93497077-047dc180-f8de-11ea-9d33-1ca24b037b28.png)

Author: @mxgrey

**Comment by ChawinTan** [comment]
If I understood the issue correctly, the issue here is to allow bigger maps to zoom further out? So by changing the `minZoom` value on the map to a lower value should suffice?

I have created a branch below to experiment with the problem but it seems like I have over-complicated it. In `handleBaseLayerChange`, I set the map to automatically zoom out on large maps and zoom in on small maps. Zooming in automatically still does not work properly yet as it takes the map out of the view port. I think what I did is probably a nice to have and not necessary at the moment though, base on my understanding of the problem

https://github.com/osrf/romi-dashboard/tree/fix/airpot-demo

**Comment by matiasbavera** [comment]
Hi @ChawinTan , Thank you for tackling this. 

> If I understood the issue correctly, the issue here is to allow bigger maps to zoom further out? So by changing the `minZoom` value on the map to a lower value should suffice?

Yeah, you're right. But that would be the patch solution.


> I have created a branch below to experiment with the problem but it seems like I have over-complicated it. In `handleBaseLayerChange`, I set the map to automatically zoom out on large maps and zoom in on small maps. Zooming in automatically still does not work properly yet as it takes the map out of the view port. I think what I did is probably a nice to have and not necessary at the moment though, base on my understanding of the problem

This would be a cool feature as you said (and if you're having problems with it you can leave it as nice to have), but another thing we should do, and I think it worth investing time, if possible, is to have a dinamic `minZoom={x} ` depending of the size of the map. E.g:

Airport ->  minZoom={getMinZoomFromMapSize()} (I think this is 2)
Office -> minZoom={getMinZoomFromMapSize()} (Let's say 4)
 
This will help us not to over zoom out. E.g:
![image](https://user-images.githubusercontent.com/11761240/93945539-21aef780-fd05-11ea-8064-82b9d6af877c.png)

This will help us cover cases where floors for the same world have different dimensions and of course usages for different worlds, without having to configure it manually.

HTH,

**Comment by koonpeng** [comment]
This can be quite tricky when we are dealing with multiple floors with different floor sizes and offsets. Should we remember the zoom levels and bounds of each floor, or should we calculate single value from all the floors?

For the zoom levels, we need to look at leaflet's zoom algorithm, iirc, each zoom level is x2 magnification, but I don't remember whats the base at zoom level 0.

**Comment by ChawinTan** [comment]
> This would be a cool feature as you said (and if you're having problems with it you can leave it as nice to have), but another thing we should do, and I think it worth investing time, if possible, is to have a dinamic `minZoom={x} ` depending of the size of the map. E.g:

This was what I was thinking at first too 

> This can be quite tricky when we are dealing with multiple floors with different floor sizes and offsets. Should we remember the zoom levels and bounds of each floor, or should we calculate single value from all the floors?
> 
> For the zoom levels, we need to look at leaflet's zoom algorithm, iirc, each zoom level is x2 magnification, but I don't remember whats the base at zoom level 0.

Yah. One thing I realize is that currently the initial bounds is only calculated once in React.memo and subsequent changes to different maps do not update the map configurations. If we need to calculate and remember the bounds of each floor, we might need to rewrite this portion significantly.

**Comment by matiasbavera** [comment]
> Yah. One thing I realize is that currently the initial bounds is only calculated once in React.memo and subsequent changes to different maps do not update the map configurations. If we need to calculate and remember the bounds of each floor, we might need to rewrite this portion significantly.

Yeah, that will be a big refactor. Lets us know what you discover =)
