### ISSUE TITLE
Store a tutorial first time user flag on browser local storage

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#122]
The idea is that the first time that a user enters the system, the tutorial is activated automatically (The tutorial should be deactivated in the subsequent accesses to the system). This I think could be achieved by storing a variable in the browser local storage that allows to know if the automatic tutorial has already been executed or not.

**Comment by koonpeng** [comment]
I think this is already the case? https://github.com/osrf/romi-dashboard/blob/d10808d31bf97700f8358323ebbeccc6d6b0111b/src/settings.ts#L33. Maybe there are bugs somewhere.

**Comment by matiasbavera** [comment]
Whoops, sorry, I wrote this issue and forgot to complete it, actually is for the tutorial. I'll describe it tomorrow. It would be just a flag though, on the user first sign in

**Comment by matiasbavera** [comment]
You're already doing something similar with the `tourComplete` variable

**Comment by matiasbavera** [comment]
Addressed
