### ISSUE TITLE
Set a consistent format name for html custom attributes

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#130]
Should we keep it with PascalCase? or Should we separate the word it with '-' as we do it with the ids
```
data-component=\\"MainMenu\\"
data-item=\\"Doors\\"
data-name=\\"main_door\\"
data-item= \\"Commands\\"
data-component=\\"LoopForm\\"

```

Example of ids:
```
id=\\"show-settings-btn\\"
id=\\"show-help-btn\\"
id=\\"help-drawer-options\\"
```

**Comment by koonpeng** [comment]
The `data-component` attr is reflecting the react component it belongs to, so it makes sense for it to be PascalCase. The others are up for debate and I don't have a preference for each of them.

In any case, many of the components are being moved to `react-components` package and they no longer requires these custom attributes.
