### ISSUE TITLE
Improve visualization of the office map

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#137]
Since we agreed to have a sandbox for the tutorial, with a particular map (which could be the office map), I think it would be interesting to improve this map (make something similar to the airport maybe), because it will be displayed in all Romi-dashboard instances that future clients will have.
Current office blueprint:

![image](https://user-images.githubusercontent.com/11761240/95614844-94c2a880-0a3d-11eb-86aa-39a550a7177f.png)

Simulation map viewed from above
![office](https://user-images.githubusercontent.com/11761240/95615135-1a465880-0a3e-11eb-991e-d09dca12287e.png)

**Comment by koonpeng** [comment]
Rendering the 3d models would require webgl and an overhaul to the schedule visualizer. Do you mean to update image of the map? The map is obtained from the building map server, which is configured by rmf_demos. I will open an issue there instead, please go ahead and close this if there is no work required on the dashboard.

**Comment by matiasbavera** [comment]
I'll open an issue in rmf_demos about this.

Sorry, I don't mean it to update the 3d model. I just intended it to replace the current photo with a vectorized blueprint like the one we have in the airport.  

![image](https://user-images.githubusercontent.com/11761240/95775997-d8195300-0c99-11eb-8c04-d7b805b1992a.png)
