### ISSUE TITLE
Create an Authentication interface

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#16]
Nice to have:
An external proprietary authentication service (let's named EPAS) will handle the authentication with OAuth. We don't have access to EPAS yet. So, if we want to make a flexible design to switch from an authentication service (like e.g: Amazon Cognito or Auth0) to EPAS, we will need an authorization interface to make further implementation easier.

**Comment by koonpeng** [comment]
now available with #79
