### ISSUE TITLE
Lift Visualization Enhancements

### ISSUE THREAD

**Issue by Yadunund** [osrf/romi-dashboard#30]
Hi @baviera08 ,

I would like to share some feedback on the visualization of lifts after running some trials.

Some general comments:
- I find the yellow of the cabin slightly alarming. Could we use something more sombre like grey instead? (personally I like the shade of grey used when the lift is not initialized)
- I think it adds more value if the `current_level` of the lift can be printed in place of `current_mode` ("Unknown" in images below). 

1.Screenshot below of lift in moving state:
![image](https://user-images.githubusercontent.com/13482049/83147637-89c04900-a12a-11ea-92a7-40666619905e.png)
-  Would be be possible to increase the transparency of the cabin so it looks like a lighter shade of grey when moving? This would help convey the `current_mode`. 
- The printout of the destination is great but it tends to get covered when the robot is inside the lift. Could we have it printed where the "Unknown" currently is? So when the lift is stationary at a level, the printout is the current_level name but if the lift is moving, it prints the destination text (L1->L3 text) at the same location.

**Comment by baviera08** [comment]
Thanks for the feedback. :)

**Comment by baviera08** [comment]
Hi @Yadunund how do you managed to have that lift with those coordinates and with that state?

I tried to test it with this config:

`rmf_core`: develop
`rmf_demos`: test/multilevel
`rmf_schedule_visualizer`: develop
`traffic_editor`: master
