### ISSUE TITLE
umbrella issue list

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#4]
backend
1. ~updating the building map server to serve the new Great Editor format (it doesn't include doors/lifts/places now) (https://github.com/osrf/traffic_editor)~
2. ~updating the trajectory websocket server to support new participant system in the `develop` branch of `rmf_core` (support is available in `develop` branch of `rmf_schedule_visualizer`, can be resolved when its tested working) (https://github.com/osrf/rmf_schedule_visualizer, https://github.com/osrf/rmf_core)~
3. ~add door/lift location and size to building map message (https://github.com/osrf/traffic_editor)~
4. robot icons and how they should be distributed (https://github.com/osrf/rmf_core)
5. better soss protocol that can handle large binary payloads (https://github.com/osrf/soss)
6. ~Publish robot level name in slotcar simulation (https://github.com/osrf/traffic_editor)~
7. identify trajectory with the robot (https://github.com/osrf/rmf_schedule_visualizer)

front end
~1. drawing doors, lifts on the map (dependent on some missing data not exposed in the building map msgs)~
~2. drawing conflicting trajectories~
3. authentication & authorization (chart will provide the backend, using oauth)
~4. more bling (perennial)~

**Comment by baviera08** [comment]
Just thinking out loud.
How do you want to deploy the project? In a server inside the location (airport) or in the cloud. I'm asking this because we can have all the assets in a file bucket (e.g: like S3), but if you want to install the project locally we cannot depend on external sources. We can also create a local bucket if that the case. 

About the drawing of conflicting trajectories, do you want to draw all possible paths (or routes) and highlight the conflicting trajectories?. How we'll know that there are conflicting trajectories? the back end will give us notice, or should we notice this in the FrontEnd. 

About Authentication and authorization, do you have any preference of an authentication service (like Auth0, Amazon Cognito, Firebase). Alejo and I have worked with Auth0 in the past.

**Comment by koonpeng** [comment]
Deployment is still up in the air, but I am going to assume we will host it on site. Some of the assets may be confidential so I doubt the owners would be comfortable hosting it on the cloud, it also interacts with the rmf core systems so there isn't much advantage to have the frontend on the cloud while the backend are hosted locally. There's a chance for it to be on a private cloud but if it were the case it would probably be in a VM or container.

[rmf_schedule_visualizer](https://github.com/osrf/rmf_schedule_visualizer) has a websocket server that provides the trajectories and conflicts. The trajectory is shows the predicted robot path as it goes through its current task, the current idea is to draw an indicator at the point of collision between conflicting robots.

chart (another player in the rmf project) will be providing the backend, all I know is that it would be based on oauth, it remains to be seen if they would use a public service. At this point I would just assume that its going to be self-hosted. We can use a public service for demo purposes while chart is coming up with the backend, but we should keep it flexible so that we can easily switch to chart's service.

**Comment by baviera08** [comment]
Thanks for the explanation @koonpeng

**Comment by Yadunund** [comment]
Hello everyone,
Quick update on the backend-related issues
- 1&3 will be addressed by this [PR](https://github.com/osrf/traffic_editor/pull/122)
- 2 is already addressed by using the `develop` branch of `rmf_schedule_visualizer`. When the `develop` branch of `rmf_core` (new participant system) is merged into `master`, the same will follow for this one.

May I understand more about the requirements for Issue 7?

**Comment by koonpeng** [comment]
> May I understand more about the requirements for Issue 7?

afaik there is no way to identify which robot a trajectory belongs to. I think the robots are uniquely identified by the robot name in `rmf_core/rmf_fleet_msgs`, we can either have the trajectory contain the robot name or have the `RobotState` message contain the trajectory id. On another note what is the `path` value representing, is that deprecated with the rmf_core traffic planning system.

**Comment by Yadunund** [comment]
@koonpeng  thanks for clarifying. The `path` field contains a list of waypoints which the robot is yet to travel to in the trajectory submitted to the schedule. The fleet adapters use the `location` field along with the waypoints in `path` to interpolate the remaining trajectory. This trajectory is compared to the original for delays and the appropriate changes are submitted to the schedule.

@mxgrey, to address the UI issue, would it make sense to add an `id` field to `PathRequest` and `RobotState` msg definitions? This way the fleet adapter can pass on the `participant id` to a robot/slotcar through the `PathRequest` which will be used to populate the same in its `RobotState`.

**Comment by mxgrey** [comment]
I think we can go in the opposite direction: The `ParticipantDescription` contains a participant name, which can be tied to the `name` field in `rmf_fleet_msgs/RobotState`. And `ParticipantDescription` also contains an `owner` name field which can be tied to the `name` field `rmf_fleet_msgs/FleetState`.

In case this isn't already established, the dashboard should target the `develop` branch of `rmf_core`.

**Comment by Yadunund** [comment]
Thanks for the feedback @mxgrey- that's a much better approach. I will get the websocket server to publish the robot name along with the corresponding trajectory details.

**Comment by aaronchongth** [comment]
Can we add to the list the planning utilities for the dashboard? I am unsure whether it should go on backend or frontend, but it works similarly to `rmf_schedule_visualizer`, with a server and the dashboard communicating with it through JSON websocket.

The server lives in here, https://github.com/osrf/rmf_schedule_visualizer/pull/45
while the dashboard side has not yet been implemented, but some fake data has been added, https://github.com/osrf/romi-dashboard/pull/6

An asana ticket as been added, named `Dashboard - planning utilities`, more information can be found there.

**Comment by koonpeng** [comment]
> Can we add to the list the planning utilities for the dashboard? I am unsure whether it should go on backend or frontend, but it works similarly to rmf_schedule_visualizer, with a server and the dashboard communicating with it through JSON websocket.

I would say this is more of an extra feature instead of an issue, its probably better to create it as a separate issue or issue list or maybe we can start a wiki.

**Comment by aaronchongth** [comment]
yup! good to know, I will keep it as a nice-to-have for now to work on for now. Thanks for the input!

**Comment by koonpeng** [comment]
closing this as the unfinished issues has their own topic now.
