### ISSUE TITLE
Authentication backend

### ISSUE THREAD

**Issue by koonpeng** [osrf/romi-dashboard#53]
Points to consider:
  * oauth is preferred, need some research on which flow is the best.
  * Need an interface to plug in with arbitrary databases. The implementations can to be out-of-tree.
  * How to bridge the authentication and authorizations to ROS2? As we have multiple roles, how can we make sure a user with only limited permissions cannot send any unauthorized ROS2 messages.
    * SOSSv2 does not support access control, once a user is authenticated, it has access to all exposed ROS2 interfaces.
    * Unknown what kind of access control SOSSv3 will allow.
  * The trajectory server has no support for WSS or any form of authentication currently.
  * How do we do user registration, and how would the process bridge into whatever security system RMF use.

**Comment by baviera08** [comment]
> * oauth is preferred, need some research on which flow is the best.

Makes sense for this case, the flow, and the implementation.

> Need an interface to plug in with arbitrary databases. The implementations can to be out-of-tree.

Are those databases ours or from the multiple robot providers?. Also which project should be in charge of managing the multiple sessions with the API of multiple robot providers? (SOSS?). I don't know if this is the right question but each provider will have their authentication system to which we will have to answer.

> How to bridge the authentication and authorizations to ROS2? As we have multiple roles, how can we make sure a user with only limited permissions cannot send any unauthorized ROS2 messages.
SOSSv2 does not support access control, once a user is authenticated, it has access to all exposed ROS2 interfaces.
Unknown what kind of access control SOSSv3 will allow.

I definitely have to know better things before I emit an opinion on this but, can we use our own "external" permission service. If all projects somehow now which user requests an action we can check the permissions for that action in the permission service. Sorry if my comment is out of place.

**Comment by koonpeng** [comment]
> Are those databases ours or from the multiple robot providers?. Also which project should be in charge of managing the multiple sessions with the API of multiple robot providers? (SOSS?). I don't know if this is the right question but each provider will have their authentication system to which we will have to answer.

Each robot vendor will have a fleet adapter which bridge the robot's interface to RMF, they will be managing sessions for their own robots there. The database that we will need to interface with are from the system integrators, maybe a integrator has an existing system that they would like to use in RMF to authenticate users.

---

> I definitely have to know better things before I emit an opinion on this but, can we use our own "external" permission service. If all projects somehow now which user requests an action we can check the permissions for that action in the permission service. Sorry if my comment is out of place.

Yes, but all RMF related projects must use a standardized permission database. fastrtps/ros2 does authentication by looking at the "subject_name" of a X509 cert, so we will need to look at how we can assign a cert to each user, and how the permission service can integrator with a external user database.

**Comment by baviera08** [comment]
> Yes, but all RMF related projects must use a standardized permission database. fastrtps/ros2 does authentication by looking at the "subject_name" of a X509 cert, so we will need to look at how we can assign a cert to each user, and how the permission service can integrate with a external user database.

Just to check if we are on the same page, we want something like the following image (maybe not exactly) but the graphic It'll work for me to understand better  

![auth2](https://user-images.githubusercontent.com/11761240/87360793-d88a3c80-c538-11ea-8b55-afc9eb24d49b.png)


A couple of questions:
* is the X509 cert between RMF projects is used for encryption or authentication, or both? 
* On the interface to the databases, with which projects would this interface connect? Only with the authentication server?.  Should the interface be a separate project?

**Comment by koonpeng** [comment]
That looks right, keep in mind that the security model in RMF has not been decided yet so all these are speculations at the moment.

> On the interface to the databases, with which projects would this interface connect? Only with the authentication server?.

I don't see any other services that those interfaces would need to connect to. Please do point it out if you foresee that it needs access to other services though.

> Should the interface be a separate project?

Yes, those interface should be separate projects, they may even be written by system integrators with closed sourced. So we need a way to communicate with arbitrary data store adapters.

**Comment by koonpeng** [comment]
result of team discussion:

* Consider various levels of users / access as well (i.e. task requester vs. robot admin)
  * Use cases are not clear at the moment, for now assume a “read-only” user role and a “read-write” admin role.
“read-only” role would not be able to publish any messages, “read-write” can publish and subscribe to all topics.

* 2 possible approaches
  * single mega soss instance with maximum access, access control is done at the soss side before the messages go into DDS
    * more performant
    * more code needed -> more attack surface
  * multiple instances of dashboard+soss for each level of access control, each instance will connect to its corresponding soss 
server, messages are sent to ros2/DDS and permissions are enforced there.
    * no extra code needed, soss can already control the list of topics/services its allowed access to from it’s config file.
    * each instance of soss can be configured to run with a SROS2 security context for extra security.

* In either case, the dashboard needs to be segmented to serve different feature sets either based on the user, or based on the deployment.
  * If based on the user, the same deployment of dashboard is used, but features are hidden based on the logged in user’s role.
    * less secure, since the dashboard is a webapp, the code is still there, the features are only hidden from view.
  * If based on deployment, a script to build a dashboard based on the intended “role”. Each deployment of dashboard will only authenticate users with the right access levels.

**Comment by koonpeng** [comment]
partly addressed by #79. Authentication is done, what's not done is role based access control (if needed). We can open another issue for it.
