### ISSUE TITLE
Lack of information of which robot collided with which

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#60]
Hi @Yadunund, in order to merge this PR https://github.com/osrf/romi-dashboard/pull/40 . We need to discuss and solve an issue related to the robot trajectory conflict.

The backend is sending us the robot trajectory information in the following format:

```
{
  "response":"trajectory",
  "conflicts": [310,311,312,313]
  "values":[
{...},
{...},
{...},
{...},
],
}
```

The problem here is that for example if robot A conflicts with robot B (310,311) and robot C conflicts with robot D (312,313), it would print A, B, C, D conflicting when there are actually 2 separate conflicts going on.

![image](https://user-images.githubusercontent.com/11761240/87342690-b03f1580-c519-11ea-859f-207019e90038.png)

As a proposal, can the backend send us a Trajectory message with the Conflict props being an array of conflicts ids.
Current = `[1,2,3,4]`
My proposal =` [[1,2],[2,3],[1,4]]`

What do you think about it? Do you have another solution in mind? 

CC: @koonpeng

**Comment by Yadunund** [comment]
Hi @baviera08

It makes sense to group participants as suggested. I have opened a ticket for this https://github.com/osrf/rmf_schedule_visualizer/issues/64

**Comment by Yadunund** [comment]
Hi @matiasbavera 

Could you try this branch and let me know if things work okay?
https://github.com/osrf/rmf_schedule_visualizer/pull/65

**Comment by matiasbavera** [comment]
Hey @Yadunund, thanks a lot for the quick response.

It's sending me the data in the correct format but not the correct information. I think it's sending me the positions of the inner array and not the value.

![image](https://user-images.githubusercontent.com/11761240/87725487-65c4cf80-c78b-11ea-9c69-5f7c1e5511d2.png)

**Comment by matiasbavera** [comment]
Maybe the problem is here? 

```
std::vector<std::vector<
    uint64_t>> VisualizerDataNode::get_server_conflicts() const
{
  std::vector<std::vector<uint64_t>> conflicts;
  for (const auto& conflict : _conflicts)
    conflicts.push_back(conflict.second);

  return conflicts;
}
```
https://github.com/osrf/rmf_schedule_visualizer/blob/addc1dac3232cfff450a260a2c9a6963de255e8e/rmf_schedule_visualizer/src/VisualizerData.cpp

**Comment by Yadunund** [comment]
Thanks for highlighting the problem. I've fixed it in this commit https://github.com/osrf/rmf_schedule_visualizer/pull/65/commits/14004f69b9e3f3b0987ada0ca88e89596c5e2a2a so please try again and let me know. 

Basically every robot is a "participant" with a unique id (`participant id`). Every trajectory submitted by a participant has an id (`route id`). Previously, the "id" key in the server response was populated with the `route id` while the ids in the "conflicts" key are the `participant ids`. So I've fixed this by making the values for the "id" key are `participant ids`. I've added a new key "route_id" to contain the `route id` of the trajectory.

**Comment by matiasbavera** [comment]
Oh, good to know, thanks for the explanation! It's working correctly now! Thanks @Yadunund 
![image](https://user-images.githubusercontent.com/11761240/87821594-17bcd400-c83e-11ea-8d15-fb97654304e1.png)

**Comment by Yadunund** [comment]
Glad to hear it's working. I've merged the branch into master so this issue can be closed.

**Comment by matiasbavera** [comment]
Thanks @Yadunund. Closing this!
