### ISSUE TITLE
ExpansionPanel, ExpansionSummary vs  Accordion, AccordionSummary (Discussion)

### ISSUE THREAD

**Issue by matiasbavera** [osrf/romi-dashboard#67]
Hi @vallq, Since you have been working with the mentioned components, do you see any advantage of one over the other?

**Comment by ChawinTan** [comment]
https://material-ui.com/api/expansion-panel/#expansionpanel-api

I believe there is no difference between `ExpansionPanel` and `Accordian` in terms of the API functionality. Material-ui renamed it to `Accordian` to follow a more common naming convention. 

Accordians are available in version `4.11.0` or higher, so if we want to migrate to `Accordians` we would need to update our material-ui core package which is currently at 4.9.4.

https://stackoverflow.com/questions/62680868/material-ui-accordion-formerly-expansiontable-component-wont-import

**Comment by ChawinTan** [comment]
Just curious @vallq , what kind of error did you see being logged in the console with the ExpansionPanel and ExpansionSummary?

**Comment by matiasbavera** [comment]
Ok, @ChawinTan and @vallq I think we can create two different GH Issues, one to update to `version 4.11.0` and another migrate to Accordions. Both of them as a backburner task with low priority. 
What do you think about it?

**Comment by ChawinTan** [comment]
I'm all for it!

**Comment by matiasbavera** [comment]
> Ok, @ChawinTan and @vallq I think we can create two different GH Issues, one to update to `version 4.11.0` and another migrate to Accordions. Both of them as a backburner task with low priority.
> What do you think about it?

Issues created. Closing this.
